#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "zaibu"
name = "Zaibu"
description.en = "Saisissez, consultez, recherchez et gardez la trace de toutes vos dégustations de bières et de vins !"
description.fr = "Saisissez, consultez, recherchez et gardez la trace de toutes vos dégustations de bières et de vins !"

version = "1.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "free"
demo = "https://zaibu-demo.lanterne-rouge.info/"
code = "https://codeberg.org/nanawel/zaibu"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/zaibu"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://codeberg.org/nanawel/zaibu/archive/main.tar.gz"
    sha256 = "363c494876dcfcde756d2f955f843292be2da4fd3a99b494871738cf2b43d83e"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "sqlite3, build-essential"
