#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing the $app..."

pushd "$install_dir"
	make build
popd

mkdir -p $install_dir/data/db
chown $app:$app $install_dir/data/db

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
